name: Run link checker on dev.fingerprint.com, fingerprint.com and public GitHub READMEs
on:
  push:
    branches:
      - main
    #   schedule:
    #     - cron: '0 * * * *' # Run every hour
  workflow_dispatch:
env:
  README_API_KEY: ${{ secrets.README_API_KEY }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  docs:
    name: Check links on dev.fingerprint.com
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      
      - name: Run link checker
        run: pnpm run checkLinks:docs

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dev-fingerprint-com.html
          path: results/dev-fingerprint-com.html
          retention-days: 30
  githubReadmes:
    name: Check links on public GitHub READMEs in the `fingerprintjs` organization
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      
      - name: Run link checker
        run: pnpm run checkLinks:github

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fingerprintjs-github-readmes.html
          path: results/fingerprintjs-github-readmes.html
          retention-days: 30
  web:
    name: Check links to our resources on fingerprint.com
    timeout-minutes: 20
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      
      - name: Run link checker
        run: pnpm run checkLinks:web

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fingerprint-com.html
          path: results/fingerprint-com.html
          retention-days: 30
  combine-artifacts:
      name: Combine all reports
      needs: [docs, githubReadmes, web]
      runs-on: ubuntu-latest
      if: always()
      
      steps:
        - name: Download all artifacts
          uses: actions/download-artifact@v4
          with:
            path: all-reports
            
        - name: Create combined archive
          run: |
            cd all-reports
            zip -r ../combined-reports.zip ./*
            
        - name: Upload combined artifact
          uses: actions/upload-artifact@v4
          with:
            name: combined-reports
            path: combined-reports.zip
            retention-days: 30
  deploy:
    name: Deploy reports to GitHub Pages
    needs: [docs, githubReadmes, web]
    runs-on: ubuntu-latest
    if: always()
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: reports
      - name: Create index page
        run: |
          cat > reports/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Link Checker Reports</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; }
              h1 { color: #333; }
              .report-list { margin-top: 20px; }
              .report-item { margin: 10px 0; }
              a { color: #0366d6; text-decoration: none; }
              a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <h1>Link Checker Reports</h1>
            <div class="report-list">
              <div class="report-item">
                <a href="dev-fingerprint-com.html/dev-fingerprint-com.html">dev.fingerprint.com Report</a>
              </div>
              <div class="report-item">
                <a href="fingerprintjs-github-readmes.html/fingerprintjs-github-readmes.html">GitHub READMEs Report</a>
              </div>
              <div class="report-item">
                <a href="fingerprint-com.html/fingerprint-com.html">fingerprint.com Report</a>
              </div>
            </div>
            <p>Last updated: <script>document.write(new Date().toLocaleString())</script></p>
          </body>
          </html>
          EOL
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
#   report-status:
#     needs: checkLinks
#     if: failure()
#     uses: fingerprintjs/dx-team-toolkit/.github/workflows/report-workflow-status.yml@v1
#     with:
#       notification_title: 'Hey, <@U04GNKK5ZTQ>! Production e2e tests on demo.fingerprint.com have {status_message}'
#       job_status: ${{ needs.e2e.result }}
#     secrets:
#       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}