name: Run link checker on dev.fingerprint.com
on:
  push:
    branches:
      - main
    #   schedule:
    #     - cron: '0 * * * *' # Run every hour
  workflow_dispatch:
env:
  README_API_KEY: ${{ secrets.README_API_KEY }}

jobs:
  checkLinks:
    name: Check links
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-environment
      
      - name: Run link checker
        run: pnpm run checkLinks:docs

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dev-fingerprint-com.html
          path: results/dev-fingerprint-com.html
          retention-days: 30
#   report-status:
#     needs: checkLinks
#     if: failure()
#     uses: fingerprintjs/dx-team-toolkit/.github/workflows/report-workflow-status.yml@v1
#     with:
#       notification_title: 'Hey, <@U04GNKK5ZTQ>! Production e2e tests on demo.fingerprint.com have {status_message}'
#       job_status: ${{ needs.e2e.result }}
#     secrets:
#       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}