name: Run Unit tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: nodemodules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: nodemodules-

      - name: 'Install pnpm'
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9

      - name: Install node modules
        shell: bash
        run: pnpm install --prefer-offline --frozen-lockfile

      - name: Run unit tests
        run: pnpm run test